# 设置当前spring的模式
spring:
  profiles:
    active: dev

# 设置调试模式
debug: false
---
# 正式环境
server:
  port: 8081

spring:
  profiles: online


---
# 开发模式
server:
  port: 8899
spring:
  profiles: dev
  # 关闭模板引擎的缓存
  thymeleaf:
    cache: false